MOCK_JOBS = [
    # Global Jobs
    {
        'id': 'mock_001',
        'title': 'Software Engineer',
        'company': 'Stripe',
        'location': 'San Francisco, CA',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '$140,000 - $180,000',
        'posted': '2 days ago',
        'description': 'We are looking for a Software Engineer to join our payments infrastructure team. You will design, build, and maintain scalable backend services that process millions of transactions per day. Strong Python or Java skills required. Experience with distributed systems and SQL databases preferred.',
        'skills': ['python', 'java', 'sql', 'distributed systems', 'api', 'docker', 'git', 'agile'],
        'apply_url': 'https://stripe.com/jobs',
        'logo': 'S',
        'logo_color': '#635BFF',
        'logo_url': 'https://www.google.com/s2/favicons?domain=stripe.com&sz=64',
    },
    {
        'id': 'mock_002',
        'title': 'Frontend Engineer',
        'company': 'Vercel',
        'location': 'Remote',
        'type': 'Full-time',
        'work_mode': 'Remote',
        'experience_level': 'Mid',
        'salary': '$120,000 - $160,000',
        'posted': '1 day ago',
        'description': 'Join Vercel as a Frontend Engineer and help build the future of web deployment. You will work closely with design and backend teams to deliver exceptional developer experiences. Deep knowledge of React, TypeScript, and modern CSS required.',
        'skills': ['react', 'typescript', 'javascript', 'css', 'node', 'git', 'testing', 'api'],
        'apply_url': 'https://vercel.com/careers',
        'logo': 'V',
        'logo_color': '#000000',
        'logo_url': 'https://www.google.com/s2/favicons?domain=vercel.com&sz=64',
    },
    {
        'id': 'mock_003',
        'title': 'Full Stack Developer',
        'company': 'Linear',
        'location': 'Remote',
        'type': 'Full-time',
        'work_mode': 'Remote',
        'experience_level': 'Mid',
        'salary': '$110,000 - $150,000',
        'posted': '3 days ago',
        'description': 'Linear is looking for a Full Stack Developer who cares deeply about product quality and developer tools. You will build features across the entire stack, from React frontend to Node.js backend. Experience with PostgreSQL and GraphQL is a plus.',
        'skills': ['react', 'node', 'javascript', 'typescript', 'sql', 'graphql', 'docker', 'git'],
        'apply_url': 'https://linear.app/careers',
        'logo': 'L',
        'logo_color': '#5E6AD2',
        'logo_url': 'https://www.google.com/s2/favicons?domain=linear.app&sz=64',
    },
    {
        'id': 'mock_004',
        'title': 'Backend Engineer',
        'company': 'PlanetScale',
        'location': 'Remote',
        'type': 'Full-time',
        'work_mode': 'Remote',
        'experience_level': 'Senior',
        'salary': '$130,000 - $170,000',
        'posted': '5 days ago',
        'description': 'PlanetScale is hiring a Backend Engineer to work on our database-as-a-service platform. You will work with Go, MySQL internals, and distributed systems at scale. Strong computer science fundamentals required.',
        'skills': ['go', 'mysql', 'sql', 'distributed systems', 'kubernetes', 'docker', 'git', 'api'],
        'apply_url': 'https://planetscale.com/careers',
        'logo': 'P',
        'logo_color': '#1F1F1F',
        'logo_url': 'https://www.google.com/s2/favicons?domain=planetscale.com&sz=64',
    },
    {
        'id': 'mock_005',
        'title': 'Data Engineer',
        'company': 'Databricks',
        'location': 'Amsterdam, Netherlands',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '$125,000 - $165,000',
        'posted': '1 week ago',
        'description': 'Join our data engineering team to build and maintain large-scale data pipelines. Experience with Apache Spark, Python, and cloud platforms (AWS/GCP) required. You will work with petabyte-scale datasets and enable analytics for enterprise customers.',
        'skills': ['python', 'spark', 'sql', 'aws', 'data pipelines', 'kafka', 'docker', 'git'],
        'apply_url': 'https://databricks.com/careers',
        'logo': 'D',
        'logo_color': '#FF3621',
        'logo_url': 'https://www.google.com/s2/favicons?domain=databricks.com&sz=64',
    },
    {
        'id': 'mock_006',
        'title': 'Machine Learning Engineer',
        'company': 'Hugging Face',
        'location': 'Paris, France / Remote',
        'type': 'Full-time',
        'work_mode': 'Remote',
        'experience_level': 'Senior',
        'salary': '$130,000 - $175,000',
        'posted': '4 days ago',
        'description': 'We are hiring an ML Engineer to help scale our model training infrastructure and contribute to open-source AI tooling. Deep knowledge of PyTorch, transformers, and distributed training required. Python expertise essential.',
        'skills': ['python', 'pytorch', 'machine learning', 'nlp', 'docker', 'aws', 'git', 'cuda'],
        'apply_url': 'https://huggingface.co/jobs',
        'logo': 'H',
        'logo_color': '#FF9D00',
        'logo_url': 'https://www.google.com/s2/favicons?domain=huggingface.co&sz=64',
    },
    {
        'id': 'mock_007',
        'title': 'DevOps Engineer',
        'company': 'HashiCorp',
        'location': 'Austin, TX',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '$120,000 - $155,000',
        'posted': '6 days ago',
        'description': 'HashiCorp is looking for a DevOps Engineer to help customers adopt our infrastructure automation tools. Strong experience with Terraform, Kubernetes, AWS, and CI/CD pipelines required.',
        'skills': ['terraform', 'kubernetes', 'docker', 'aws', 'ci/cd', 'python', 'linux', 'git'],
        'apply_url': 'https://hashicorp.com/jobs',
        'logo': 'H',
        'logo_color': '#1563FF',
        'logo_url': 'https://www.google.com/s2/favicons?domain=hashicorp.com&sz=64',
    },
    {
        'id': 'mock_008',
        'title': 'Product Engineer',
        'company': 'Notion',
        'location': 'New York, NY',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '$135,000 - $170,000',
        'posted': '2 days ago',
        'description': 'Notion is looking for a Product Engineer who combines strong engineering with product intuition. You will own features end-to-end, from design to deployment. React, TypeScript, and Node.js experience required.',
        'skills': ['react', 'typescript', 'node', 'javascript', 'sql', 'api', 'git', 'agile'],
        'apply_url': 'https://notion.so/jobs',
        'logo': 'N',
        'logo_color': '#000000',
        'logo_url': 'https://www.google.com/s2/favicons?domain=notion.so&sz=64',
    },
    {
        'id': 'mock_009',
        'title': 'iOS Developer',
        'company': 'Airbnb',
        'location': 'San Francisco, CA',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Senior',
        'salary': '$150,000 - $195,000',
        'posted': '3 days ago',
        'description': 'Airbnb is hiring an iOS Developer to build the next generation of our mobile product. Deep knowledge of Swift, SwiftUI, and Objective-C required. Experience with performance optimization and accessibility standards preferred.',
        'skills': ['swift', 'swiftui', 'ios', 'xcode', 'objective-c', 'git', 'agile', 'api'],
        'apply_url': 'https://airbnb.com/careers',
        'logo': 'A',
        'logo_color': '#FF5A5F',
        'logo_url': 'https://www.google.com/s2/favicons?domain=airbnb.com&sz=64',
    },
    {
        'id': 'mock_010',
        'title': 'Android Developer',
        'company': 'Spotify',
        'location': 'Stockholm, Sweden',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '$115,000 - $150,000',
        'posted': '1 week ago',
        'description': 'Join Spotify engineering to build music experiences for millions of Android users. Strong Kotlin skills required, with experience in Jetpack Compose and clean architecture patterns.',
        'skills': ['kotlin', 'android', 'jetpack compose', 'java', 'git', 'api', 'testing', 'agile'],
        'apply_url': 'https://spotify.com/jobs',
        'logo': 'S',
        'logo_color': '#1DB954',
        'logo_url': 'https://www.google.com/s2/favicons?domain=spotify.com&sz=64',
    },
    {
        'id': 'mock_011',
        'title': 'Security Engineer',
        'company': 'Cloudflare',
        'location': 'London, UK / Remote',
        'type': 'Full-time',
        'work_mode': 'Remote',
        'experience_level': 'Senior',
        'salary': '$140,000 - $180,000',
        'posted': '5 days ago',
        'description': 'Cloudflare is seeking a Security Engineer to protect global infrastructure. Experience with network security, penetration testing, OWASP principles, and secure coding practices required.',
        'skills': ['security', 'python', 'linux', 'networking', 'cryptography', 'docker', 'git', 'aws'],
        'apply_url': 'https://cloudflare.com/careers',
        'logo': 'C',
        'logo_color': '#F38020',
        'logo_url': 'https://www.google.com/s2/favicons?domain=cloudflare.com&sz=64',
    },
    {
        'id': 'mock_012',
        'title': 'Site Reliability Engineer',
        'company': 'GitHub',
        'location': 'Remote',
        'type': 'Full-time',
        'work_mode': 'Remote',
        'experience_level': 'Senior',
        'salary': '$145,000 - $185,000',
        'posted': '2 days ago',
        'description': 'GitHub is hiring an SRE to maintain reliability of the world largest developer platform. Strong systems engineering background, experience with incident management, and on-call ownership required.',
        'skills': ['kubernetes', 'docker', 'aws', 'python', 'go', 'monitoring', 'linux', 'git'],
        'apply_url': 'https://github.com/about/careers',
        'logo': 'G',
        'logo_color': '#24292E',
        'logo_url': 'https://www.google.com/s2/favicons?domain=github.com&sz=64',
    },
    {
        'id': 'mock_013',
        'title': 'UI/UX Engineer',
        'company': 'Figma',
        'location': 'San Francisco, CA',
        'type': 'Full-time',
        'work_mode': 'On-site',
        'experience_level': 'Mid',
        'salary': '$130,000 - $165,000',
        'posted': '4 days ago',
        'description': 'Figma is looking for a UI/UX Engineer who bridges design and engineering. Excellent React skills combined with design sensibility required. Experience with design systems and accessibility at scale preferred.',
        'skills': ['react', 'typescript', 'css', 'javascript', 'design systems', 'figma', 'git', 'testing'],
        'apply_url': 'https://figma.com/careers',
        'logo': 'F',
        'logo_color': '#F24E1E',
        'logo_url': 'https://www.google.com/s2/favicons?domain=figma.com&sz=64',
    },
    {
        'id': 'mock_014',
        'title': 'Blockchain Engineer',
        'company': 'Coinbase',
        'location': 'Remote',
        'type': 'Full-time',
        'work_mode': 'Remote',
        'experience_level': 'Senior',
        'salary': '$155,000 - $200,000',
        'posted': '1 week ago',
        'description': 'Coinbase is hiring a Blockchain Engineer to build secure financial infrastructure. Strong understanding of Ethereum, Solidity, and cryptographic protocols required. Go or Rust experience a plus.',
        'skills': ['solidity', 'ethereum', 'python', 'go', 'rust', 'sql', 'docker', 'git'],
        'apply_url': 'https://coinbase.com/careers',
        'logo': 'C',
        'logo_color': '#0052FF',
        'logo_url': 'https://www.google.com/s2/favicons?domain=coinbase.com&sz=64',
    },
    {
        'id': 'mock_015',
        'title': 'Platform Engineer',
        'company': 'Shopify',
        'location': 'Ottawa, Canada / Remote',
        'type': 'Full-time',
        'work_mode': 'Remote',
        'experience_level': 'Mid',
        'salary': '$120,000 - $160,000',
        'posted': '3 days ago',
        'description': 'Shopify needs a Platform Engineer to scale commerce infrastructure for millions of merchants. Ruby on Rails, Go, and Kubernetes experience required. Strong knowledge of distributed systems and caching layers.',
        'skills': ['ruby', 'go', 'kubernetes', 'docker', 'sql', 'redis', 'aws', 'git'],
        'apply_url': 'https://shopify.com/careers',
        'logo': 'S',
        'logo_color': '#96BF48',
        'logo_url': 'https://www.google.com/s2/favicons?domain=shopify.com&sz=64',
    },

    # Indian Jobs
    {
        'id': 'india_001',
        'title': 'Software Development Engineer',
        'company': 'Razorpay',
        'location': 'Bengaluru, Karnataka',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '₹18,00,000 - ₹28,00,000',
        'posted': '1 day ago',
        'description': 'Razorpay is seeking an SDE to build payment infrastructure serving millions of businesses. Strong backend skills in Go or Java required. Experience with distributed systems, payment gateways, and high-throughput APIs preferred.',
        'skills': ['java', 'go', 'python', 'sql', 'kafka', 'redis', 'docker', 'api'],
        'apply_url': 'https://razorpay.com/jobs',
        'logo': 'R',
        'logo_color': '#2B6CB0',
        'logo_url': 'https://www.google.com/s2/favicons?domain=razorpay.com&sz=64',
    },
    {
        'id': 'india_002',
        'title': 'Senior Frontend Engineer',
        'company': 'CRED',
        'location': 'Bengaluru, Karnataka',
        'type': 'Full-time',
        'work_mode': 'On-site',
        'experience_level': 'Senior',
        'salary': '₹25,00,000 - ₹40,00,000',
        'posted': '2 days ago',
        'description': 'CRED is hiring a Senior Frontend Engineer to craft premium financial experiences. You will work with React, TypeScript and design pixel-perfect UIs. Strong eye for design combined with engineering rigor required.',
        'skills': ['react', 'typescript', 'javascript', 'css', 'performance', 'git', 'testing', 'api'],
        'apply_url': 'https://cred.club/jobs',
        'logo': 'C',
        'logo_color': '#1A1A1A',
        'logo_url': 'https://www.google.com/s2/favicons?domain=cred.club&sz=64',
    },
    {
        'id': 'india_003',
        'title': 'Backend Engineer',
        'company': 'Swiggy',
        'location': 'Bengaluru, Karnataka',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '₹15,00,000 - ₹24,00,000',
        'posted': '3 days ago',
        'description': 'Swiggy is looking for a Backend Engineer to scale food delivery infrastructure. Experience with Java/Go microservices, event-driven architecture, and NoSQL databases required. Ability to handle millions of concurrent users is a must.',
        'skills': ['java', 'go', 'microservices', 'kafka', 'mongodb', 'redis', 'docker', 'kubernetes'],
        'apply_url': 'https://careers.swiggy.com',
        'logo': 'S',
        'logo_color': '#FC8019',
        'logo_url': 'https://www.google.com/s2/favicons?domain=swiggy.com&sz=64',
    },
    {
        'id': 'india_004',
        'title': 'Data Scientist',
        'company': 'PhonePe',
        'location': 'Bengaluru, Karnataka',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '₹20,00,000 - ₹32,00,000',
        'posted': '1 week ago',
        'description': 'PhonePe needs a Data Scientist to build fraud detection and personalization models for 500M+ users. Strong Python, ML, and statistical modelling skills required. Experience with large-scale data using Spark or Hive preferred.',
        'skills': ['python', 'machine learning', 'spark', 'sql', 'statistics', 'sklearn', 'git', 'aws'],
        'apply_url': 'https://phonepe.com/careers',
        'logo': 'P',
        'logo_color': '#5F259F',
        'logo_url': 'https://www.google.com/s2/favicons?domain=phonepe.com&sz=64',
    },
    {
        'id': 'india_005',
        'title': 'Full Stack Developer',
        'company': 'Meesho',
        'location': 'Bengaluru, Karnataka',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Entry',
        'salary': '₹10,00,000 - ₹18,00,000',
        'posted': '2 days ago',
        'description': 'Meesho is hiring a Full Stack Developer to build e-commerce features for Tier 2/3 India. React frontend with Node.js or Java backend. Experience with building mobile-first responsive UIs required.',
        'skills': ['react', 'node', 'javascript', 'sql', 'html', 'css', 'git', 'agile'],
        'apply_url': 'https://meesho.io/jobs',
        'logo': 'M',
        'logo_color': '#9C27B0',
        'logo_url': 'https://www.google.com/s2/favicons?domain=meesho.com&sz=64',
    },
    {
        'id': 'india_006',
        'title': 'SDE-2 Backend',
        'company': 'Zepto',
        'location': 'Mumbai, Maharashtra',
        'type': 'Full-time',
        'work_mode': 'On-site',
        'experience_level': 'Mid',
        'salary': '₹18,00,000 - ₹28,00,000',
        'posted': '4 days ago',
        'description': 'Zepto is seeking SDE-2 engineers to build 10-minute delivery infrastructure. Strong Java/Go backend skills with experience in real-time systems and geospatial data handling required.',
        'skills': ['java', 'go', 'sql', 'redis', 'kafka', 'docker', 'microservices', 'api'],
        'apply_url': 'https://zepto.com/careers',
        'logo': 'Z',
        'logo_color': '#8B5CF6',
        'logo_url': 'https://www.google.com/s2/favicons?domain=zepto.com&sz=64',
    },
    {
        'id': 'india_007',
        'title': 'Software Engineer',
        'company': 'Groww',
        'location': 'Bengaluru, Karnataka',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '₹16,00,000 - ₹26,00,000',
        'posted': '5 days ago',
        'description': 'Groww is building the next generation investment platform. Looking for backend engineers with strong Java/Kotlin skills and experience in financial domain, real-time data processing, and high-reliability systems.',
        'skills': ['java', 'kotlin', 'spring boot', 'sql', 'kafka', 'redis', 'docker', 'aws'],
        'apply_url': 'https://groww.in/careers',
        'logo': 'G',
        'logo_color': '#00D09C',
        'logo_url': 'https://www.google.com/s2/favicons?domain=groww.in&sz=64',
    },
    {
        'id': 'india_008',
        'title': 'Senior Software Engineer',
        'company': 'Flipkart',
        'location': 'Bengaluru, Karnataka',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Senior',
        'salary': '₹28,00,000 - ₹45,00,000',
        'posted': '1 week ago',
        'description': 'Flipkart is hiring senior engineers for its supply chain and logistics platform. Java microservices expertise with distributed systems knowledge required. Experience at scale (millions of orders/day) a strong advantage.',
        'skills': ['java', 'microservices', 'kafka', 'elasticsearch', 'sql', 'docker', 'kubernetes', 'aws'],
        'apply_url': 'https://flipkartcareers.com',
        'logo': 'F',
        'logo_color': '#2874F0',
        'logo_url': 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
    },
    {
        'id': 'india_009',
        'title': 'React Developer',
        'company': 'Zomato',
        'location': 'Gurugram, Haryana',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '₹14,00,000 - ₹22,00,000',
        'posted': '3 days ago',
        'description': 'Zomato is looking for a React Developer to build food discovery and ordering experiences. Strong React, Redux, and performance optimization skills required. Experience with mobile web and PWAs a plus.',
        'skills': ['react', 'javascript', 'typescript', 'redux', 'css', 'node', 'git', 'testing'],
        'apply_url': 'https://zomato.com/careers',
        'logo': 'Z',
        'logo_color': '#E23744',
        'logo_url': 'https://www.google.com/s2/favicons?domain=zomato.com&sz=64',
    },
    {
        'id': 'india_010',
        'title': 'DevOps Engineer',
        'company': 'Ola',
        'location': 'Bengaluru, Karnataka',
        'type': 'Full-time',
        'work_mode': 'On-site',
        'experience_level': 'Mid',
        'salary': '₹14,00,000 - ₹22,00,000',
        'posted': '6 days ago',
        'description': 'Ola is hiring a DevOps Engineer to manage infrastructure for ride-hailing at scale. Experience with Kubernetes, Terraform, and AWS/GCP required. Strong automation mindset and CI/CD pipeline experience essential.',
        'skills': ['kubernetes', 'docker', 'terraform', 'aws', 'ci/cd', 'python', 'linux', 'monitoring'],
        'apply_url': 'https://olacabs.com/careers',
        'logo': 'O',
        'logo_color': '#009E3D',
        'logo_url': 'https://www.google.com/s2/favicons?domain=olacabs.com&sz=64',
    },
    {
        'id': 'india_011',
        'title': 'SDE-1 (Fresher)',
        'company': 'TCS',
        'location': 'Pune, Maharashtra',
        'type': 'Full-time',
        'work_mode': 'On-site',
        'experience_level': 'Entry',
        'salary': '₹3,50,000 - ₹7,00,000',
        'posted': '1 day ago',
        'description': 'TCS is hiring SDE-1 freshers for digital transformation projects. Strong fundamentals in data structures, algorithms, and at least one programming language required. Training provided for new graduates.',
        'skills': ['java', 'python', 'sql', 'data structures', 'algorithms', 'git', 'agile'],
        'apply_url': 'https://tcs.com/careers',
        'logo': 'T',
        'logo_color': '#0067B1',
        'logo_url': 'https://www.google.com/s2/favicons?domain=tcs.com&sz=64',
    },
    {
        'id': 'india_012',
        'title': 'Associate Software Engineer',
        'company': 'Infosys',
        'location': 'Hyderabad, Telangana',
        'type': 'Full-time',
        'work_mode': 'On-site',
        'experience_level': 'Entry',
        'salary': '₹3,60,000 - ₹6,50,000',
        'posted': '2 days ago',
        'description': 'Infosys is hiring freshers and early-career engineers for its digital delivery centers. Java/.NET development skills preferred. Candidates with CGPA above 7.0 from any CS/IT background encouraged to apply.',
        'skills': ['java', '.net', 'sql', 'html', 'css', 'javascript', 'git', 'agile'],
        'apply_url': 'https://infosys.com/careers',
        'logo': 'I',
        'logo_color': '#007DC6',
        'logo_url': 'https://www.google.com/s2/favicons?domain=infosys.com&sz=64',
    },
    {
        'id': 'india_013',
        'title': 'Cloud Engineer',
        'company': 'Wipro',
        'location': 'Chennai, Tamil Nadu',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '₹8,00,000 - ₹14,00,000',
        'posted': '4 days ago',
        'description': 'Wipro needs a Cloud Engineer to help enterprise clients migrate to AWS/Azure. Experience with cloud architecture, IaC (Terraform/CloudFormation), and Linux administration required.',
        'skills': ['aws', 'azure', 'terraform', 'linux', 'docker', 'python', 'networking', 'git'],
        'apply_url': 'https://wipro.com/careers',
        'logo': 'W',
        'logo_color': '#341C6A',
        'logo_url': 'https://www.google.com/s2/favicons?domain=wipro.com&sz=64',
    },
    {
        'id': 'india_014',
        'title': 'Software Engineer - Remote India',
        'company': 'Atlassian',
        'location': 'Remote India',
        'type': 'Full-time',
        'work_mode': 'Remote',
        'experience_level': 'Mid',
        'salary': '₹22,00,000 - ₹35,00,000',
        'posted': '3 days ago',
        'description': 'Atlassian is hiring remote India-based engineers for Jira and Confluence product teams. Strong Java or Python backend skills with experience in cloud-native development and agile delivery required.',
        'skills': ['java', 'python', 'sql', 'aws', 'docker', 'kubernetes', 'git', 'agile'],
        'apply_url': 'https://atlassian.com/company/careers',
        'logo': 'A',
        'logo_color': '#0052CC',
        'logo_url': 'https://www.google.com/s2/favicons?domain=atlassian.com&sz=64',
    },
    {
        'id': 'india_015',
        'title': 'Product Engineer',
        'company': 'Postman',
        'location': 'Bengaluru, Karnataka',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '₹20,00,000 - ₹32,00,000',
        'posted': '5 days ago',
        'description': 'Postman is looking for Product Engineers to build the world best API development tool. Strong React and Node.js skills required. Passion for developer experience and building high-quality tools essential.',
        'skills': ['react', 'node', 'javascript', 'typescript', 'electron', 'api', 'git', 'testing'],
        'apply_url': 'https://postman.com/careers',
        'logo': 'P',
        'logo_color': '#FF6C37',
        'logo_url': 'https://www.google.com/s2/favicons?domain=postman.com&sz=64',
    },

    # Data & Analytics roles — India
    {
        'id': 'india_016',
        'title': 'Data Analyst',
        'company': 'Walmart Global Tech',
        'location': 'Bengaluru, Karnataka',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '₹12,00,000 - ₹20,00,000',
        'posted': '2 days ago',
        'description': 'Walmart Global Tech is hiring a Data Analyst to drive business insights for retail operations. You will work with large datasets to build dashboards, perform cohort analysis, and generate actionable reports. Proficiency in SQL, Python, and Tableau required. Experience with A/B testing and funnel analysis preferred.',
        'skills': ['sql', 'python', 'tableau', 'excel', 'data analysis', 'statistics', 'power bi', 'git'],
        'apply_url': 'https://careers.walmart.com',
        'logo': 'W',
        'logo_color': '#0071CE',
        'logo_url': 'https://www.google.com/s2/favicons?domain=walmart.com&sz=64',
    },
    {
        'id': 'india_017',
        'title': 'Senior Data Analyst',
        'company': 'HDFC Bank',
        'location': 'Mumbai, Maharashtra',
        'type': 'Full-time',
        'work_mode': 'On-site',
        'experience_level': 'Senior',
        'salary': '₹15,00,000 - ₹25,00,000',
        'posted': '3 days ago',
        'description': 'HDFC Bank is seeking a Senior Data Analyst for its analytics center of excellence. You will analyze transaction data, model customer behavior, and support product and risk teams with data-driven insights. Expertise in SQL, Python, and Power BI required. Financial domain experience preferred.',
        'skills': ['sql', 'python', 'power bi', 'excel', 'data analysis', 'statistics', 'machine learning', 'tableau'],
        'apply_url': 'https://hdfcbank.com/careers',
        'logo': 'H',
        'logo_color': '#004C8F',
        'logo_url': 'https://www.google.com/s2/favicons?domain=hdfcbank.com&sz=64',
    },
    {
        'id': 'india_018',
        'title': 'Product Manager',
        'company': 'Myntra',
        'location': 'Bengaluru, Karnataka',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '₹22,00,000 - ₹38,00,000',
        'posted': '4 days ago',
        'description': 'Myntra is looking for a Product Manager to drive growth of its fashion discovery product. You will own the product roadmap, collaborate with design and engineering, and use data to prioritize features. Strong analytical skills, user empathy, and experience with agile delivery required.',
        'skills': ['product management', 'analytics', 'sql', 'agile', 'user research', 'roadmap', 'jira', 'figma'],
        'apply_url': 'https://myntra.com/careers',
        'logo': 'M',
        'logo_color': '#FF3F6C',
        'logo_url': 'https://www.google.com/s2/favicons?domain=myntra.com&sz=64',
    },
    {
        'id': 'india_019',
        'title': 'Business Analyst',
        'company': 'Accenture',
        'location': 'Hyderabad, Telangana',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Entry',
        'salary': '₹6,00,000 - ₹10,00,000',
        'posted': '1 day ago',
        'description': 'Accenture is hiring Business Analysts for its digital consulting practice. You will gather requirements, analyze business processes, and translate insights into functional specifications for technology teams. SQL, Excel, and process modeling skills required.',
        'skills': ['sql', 'excel', 'business analysis', 'powerpoint', 'data analysis', 'jira', 'agile', 'communication'],
        'apply_url': 'https://accenture.com/in-en/careers',
        'logo': 'A',
        'logo_color': '#A100FF',
        'logo_url': 'https://www.google.com/s2/favicons?domain=accenture.com&sz=64',
    },
    {
        'id': 'india_020',
        'title': 'ML Engineer',
        'company': 'Amazon',
        'location': 'Hyderabad, Telangana',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Senior',
        'salary': '₹30,00,000 - ₹55,00,000',
        'posted': '5 days ago',
        'description': 'Amazon is hiring a Machine Learning Engineer to build production ML systems for Alexa and recommendations. You will own model training pipelines, optimize inference latency, and ship models to millions of customers. Deep Python, PyTorch, and AWS SageMaker experience required.',
        'skills': ['python', 'pytorch', 'machine learning', 'aws', 'sagemaker', 'sql', 'docker', 'mlops'],
        'apply_url': 'https://amazon.jobs',
        'logo': 'A',
        'logo_color': '#FF9900',
        'logo_url': 'https://www.google.com/s2/favicons?domain=amazon.com&sz=64',
    },
    {
        'id': 'india_021',
        'title': 'QA Engineer',
        'company': 'Microsoft',
        'location': 'Hyderabad, Telangana',
        'type': 'Full-time',
        'work_mode': 'Hybrid',
        'experience_level': 'Mid',
        'salary': '₹16,00,000 - ₹26,00,000',
        'posted': '2 days ago',
        'description': 'Microsoft is looking for a QA Engineer to ensure quality of cloud products at scale. You will design test plans, build automated test frameworks, and collaborate with engineers to shift quality left. Strong experience with Selenium, pytest, and CI/CD pipelines required.',
        'skills': ['selenium', 'python', 'pytest', 'testing', 'automation', 'ci/cd', 'git', 'azure'],
        'apply_url': 'https://careers.microsoft.com',
        'logo': 'M',
        'logo_color': '#00A4EF',
        'logo_url': 'https://www.google.com/s2/favicons?domain=microsoft.com&sz=64',
    },

    # Data & Analytics roles — Global
    {
        'id': 'mock_016',
        'title': 'Data Analyst',
        'company': 'Airbnb',
        'location': 'Remote',
        'type': 'Full-time',
        'work_mode': 'Remote',
        'experience_level': 'Mid',
        'salary': '$110,000 - $145,000',
        'posted': '2 days ago',
        'description': 'Airbnb is seeking a Data Analyst to drive insights across the marketplace. You will build dashboards, run experiments, and work with product teams to optimize host and guest experiences. Fluency in SQL and Python required, with experience in Tableau or Looker preferred. Strong statistical thinking and A/B testing knowledge essential.',
        'skills': ['sql', 'python', 'tableau', 'statistics', 'data analysis', 'looker', 'excel', 'git'],
        'apply_url': 'https://airbnb.com/careers',
        'logo': 'A',
        'logo_color': '#FF5A5F',
        'logo_url': 'https://www.google.com/s2/favicons?domain=airbnb.com&sz=64',
    },
    {
        'id': 'mock_017',
        'title': 'Product Manager',
        'company': 'Atlassian',
        'location': 'Remote',
        'type': 'Full-time',
        'work_mode': 'Remote',
        'experience_level': 'Senior',
        'salary': '$160,000 - $210,000',
        'posted': '3 days ago',
        'description': 'Atlassian is hiring a Senior Product Manager for Jira. You will set product vision, define the roadmap, and work closely with design, engineering, and GTM teams. Deep experience with B2B SaaS product management and strong analytical skills required.',
        'skills': ['product management', 'analytics', 'sql', 'agile', 'roadmap', 'user research', 'jira', 'figma'],
        'apply_url': 'https://atlassian.com/company/careers',
        'logo': 'A',
        'logo_color': '#0052CC',
        'logo_url': 'https://www.google.com/s2/favicons?domain=atlassian.com&sz=64',
    },
]


def _score_job(job, tokens):
    """Score a job against query tokens. Returns (score, include).
    Requires at least one token to appear in the job title.
    Title matches are weighted highest; full-text matches add secondary score."""
    title = job['title'].lower()
    skills_text = ' '.join(job['skills']).lower()
    full_text = ' '.join([
        title,
        job['company'].lower(),
        job['description'].lower(),
        skills_text,
        job.get('experience_level', '').lower(),
    ])
    title_hits = sum(1 for tok in tokens if tok in title)
    skill_hits = sum(1 for tok in tokens if tok in skills_text)
    full_hits  = sum(1 for tok in tokens if tok in full_text)
    # Must have at least one token in the title to be considered relevant
    if title_hits == 0:
        return 0, False
    score = title_hits * 10 + skill_hits * 3 + full_hits
    return score, True


def search_mock_jobs(query='', location=''):
    results = MOCK_JOBS[:]

    if query:
        tokens = [t.strip() for t in query.lower().split() if len(t.strip()) > 1]
        if tokens:
            scored = [(j, _score_job(j, tokens)) for j in results]
            scored = [(j, s) for j, (s, ok) in scored if ok]
            scored.sort(key=lambda x: x[1], reverse=True)
            results = [j for j, _ in scored]

    if location:
        loc = location.lower()
        results = [j for j in results if loc in j['location'].lower()]

    return results
